### ISSUE TITLE
ITs should not use port 8080

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-deployer-mesos#23]
There is an issue with MarathonTestSupport that hijacks port 8080 (when it really doesn't need to)

**Comment by ericbottard** [comment]
see https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/d4a644db19d53e5a5cb3e2a4ba0d12dfde1c7bc0

**Comment by trisberg** [comment]
I've seen same/similar issue for the K8s tests
