### ISSUE TITLE
Inconsistency between properties prefixes?

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-deployer-mesos#41]
The prefix for the global `MarathonAppDeployerProperties` bean is `"spring.cloud.deployer.mesos.marathon"` [(here)](https://github.com/spring-cloud/spring-cloud-deployer-mesos/blob/c9e227a5d617cf3d4ec4fdcc4534536625a95cd8/src/main/java/org/springframework/cloud/deployer/spi/mesos/marathon/MarathonAppDeployerProperties.java#L27) while the prefix used per-app is `"spring.cloud.deployer.marathon"` (eg [here](https://github.com/spring-cloud/spring-cloud-deployer-mesos/blob/c9e227a5d617cf3d4ec4fdcc4534536625a95cd8/src/main/java/org/springframework/cloud/deployer/spi/mesos/marathon/MarathonAppDeployer.java#L291))

Is this intentional?

**Comment by trisberg** [comment]
Not intentional, we should fix this and use "spring.cloud.deployer.mesos.marathon" everywhere
