### ISSUE TITLE
Implement Mesos TaskLauncher

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-mesos#5]
As a developer, I'd like to implement `TaskLauncher` contracts for mesos deployer.

**Acceptance:**
- `launch()` API allows launching Task applications
- `status()` API queries the current state of the Task application
- `delete()/destroy()` API removes the running Task application
- Unit tests included
- Docs included

**Comment by trisberg** [comment]
For this we need a Java library for accessing Chronos - see #20
