### ISSUE TITLE
Release gap between Spring cloud deployer mesos and Spring cloud dataflow?

### ISSUE THREAD

**Issue by geez** [spring-cloud/spring-cloud-deployer-mesos#61]
Hi all,
Just wondering about the gap in releases between spring cloud dataflow for mesos (1.0.0) and the main project (1.4.0)?
Last GA release here is June 2016 and the main spring cloud dataflow project has had many releases since (https://github.com/spring-cloud/spring-cloud-dataflow/releases).

Any plan to catch up on release versions?
We're considering this in production but obviously have some concerns, would be great to have some feedback.

**Comment by sabbyanandan** [comment]
Hi, @geez. Thanks for the interest in Mesos implementation of Deployer/SCDF! 

We haven't been able to make progress on mesos-deployer/mesos-server for a variety of reasons. The most pressing would be the fact that the general market momentum wrt container orchestration platforms. A vast majority of the consolidation appears to be moving towards Kubernetes (including: [Mesosphere](https://mesosphere.com/blog/kubernetes-dcos/) and our very own [PKS](https://pivotal.io/platform/pivotal-container-service)).

As you can imagine, it is a significant effort for us to bring the mesos-deployer and mesos-server combinations to the latest spring-cloud-deployer and spring-cloud-dataflow dependencies respectively, which is a sizeable work, but we are focused on other platforms right now. 

It'd be recommended that you switch to SCDF's Kubernetes (latest: v1.4.0) or Cloud Foundry (latest: v1.4.0), as they're actively maintained/supported with upstream dependencies, new-features, enhancements, and bug-fixes.

**Comment by geez** [comment]
@sabbyanandan Thanks for letting us know!

**Comment by sabbyanandan** [comment]
No problem! Let us know if you have any questions pertaining to K8S or CF. One of us would be online at Gitter/StackOverflow.
